name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: add target
      run: rustup target add wasm32-unknown-unknown
    - name: Build
      run: cargo build --target wasm32-unknown-unknown --release
    - name: Checkout private action repo
      uses: actions/checkout@v4
      with:
        repository: bbb0ttle/release-bbp-action
        ref: 'v0.0.5'
        token: ${{ secrets.ACTION_PAT }}
    - name: Use private action
      uses: ./ # Use the local path for the checked-out action
      with:
        who-to-greet: 'bbki.ng'
