name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: release
      uses: bbbottle/release-bbp-action@v1.0.12
      with:
        wasmArtifactName: wasm-file
        wasmFileName: bbp_now.wasm
        OSS_ACCESS_KEY_ID: ${{ secrets.OSS_ACCESS_KEY_ID }}
        OSS_ACCESS_KEY_SECRET: ${{ secrets.OSS_ACCESS_KEY_SECRET }}
        OSS_BUCKET_NAME: ${{ secrets.OSS_BUCKET_NAME }}
        OSS_BUCKET_ENDPOINT: ${{ secrets.OSS_BUCKET_ENDPOINT }}
        OSS_REGION: ${{ secrets.OSS_REGION }}
