name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: add target
      run: rustup target add wasm32-unknown-unknown
    - name: Build
      run: cargo build --target wasm32-unknown-unknown --release
    - name: Upload .wasm file
      uses: actions/upload-artifact@v4
      with:
        name: wasm-file
        path: target/wasm32-unknown-unknown/release/*.wasm
    - name: Upload plugin.json file
      uses: actions/upload-artifact@v4
      with:
        name: plugin-config
        path: plugin.json

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout release action
      uses: actions/checkout@v4
      with:
        repository: bbb0ttle/release-bbp-action
        ref: 'v0.1.0'
        token: ${{ secrets.ACTION_PAT }}
    - name: release plugin
      uses: ./ # Use the local path for the checked-out action
      with:
        wasmArtifactName: wasm-file
        wasmFileName: plugin-now.wasm
