name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: add target
      run: rustup target add wasm32-unknown-unknown
    - name: Build
      run: cargo build --target wasm32-unknown-unknown --release
    - name: Use private action
      uses: bbb0ttle/release-bbp-action@main
      with:
        who-to-greet: 'bbki.ng'
      env:
        GITHUB_TOKEN: ${{ secrets.ACTION_PAT }}
