name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: build
      uses: bbbottle/release-bbp-action@build
    - name: release
      uses: bbbottle/release-bbp-action@v1.0.19
      with:
        token: ${{ secrets.VERCEL_TOKEN }}
