name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: add target
      run: rustup target add wasm32-unknown-unknown
    - name: Build
      run: cargo build --target wasm32-unknown-unknown --release
    - name: Upload .wasm file
      uses: actions/upload-artifact@v4
      with:
        name: wasm-file
        path: target/wasm32-unknown-unknown/release/*.wasm
    - name: Upload plugin.json file
      uses: actions/upload-artifact@v4
      with:
        name: plugin-config
        path: plugin.json
    - name: release
      uses: bbbottle/release-bbp-action@v1.0.6
      with:
        wasmArtifactName: wasm-file
        wasmFileName: bbp_now.wasm
        OSS_ACCESS_KEY_ID: ${{ secrets.OSS_ACCESS_KEY_ID }}
        OSS_ACCESS_KEY_SECRET: ${{ secrets.OSS_ACCESS_KEY_SECRET }}
        OSS_BUCKET_NAME: ${{ secrets.OSS_BUCKET_NAME }}
        OSS_BUCKET_ENDPOINT: ${{ secrets.OSS_BUCKET_ENDPOINT }}
        OSS_REGION: ${{ secrets.OSS_REGION }}
